### ISSUE TITLE
Fails to build with GHC 8.6

### ISSUE THREAD

**Issue by neilmayhew** [chrisdone/jl#16]
This is due to the introduction of `MonadFail`. `generateTypeVariable` contains a pattern match that can fail, but `MonadFail` isn't in the constraints:

```
src/JL/Inferer.hs:121:3: error:
    • Could not deduce (Control.Monad.Fail.MonadFail m)
        arising from a do statement
        with the failable pattern ‘v : vs’
      from the context: MonadState [TypeVariable] m
        bound by the type signature for:
                   generateTypeVariable :: forall (m :: * -> *).
                                           MonadState [TypeVariable] m =>
                                           m TypeVariable
        at src/JL/Inferer.hs:(117,1)-(119,19)
      Possible fix:
        add (Control.Monad.Fail.MonadFail m) to the context of
          the type signature for:
            generateTypeVariable :: forall (m :: * -> *).
                                    MonadState [TypeVariable] m =>
                                    m TypeVariable
    • In a stmt of a 'do' block: v : vs <- get
      In the expression:
        do v : vs <- get
           put vs
           pure v
      In an equation for ‘generateTypeVariable’:
          generateTypeVariable
            = do v : vs <- get
                 put vs
                 pure v
    |
121 |   v:vs <- get
    |   ^^^^^^^^^^^
```

**Comment by neilmayhew** [comment]
Hey, Chris, any chance of a new release that includes this? It makes packaging easier to be able to use a tag rather than a hash. Thanks.
